version: '2'
services:
  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dumps/fresh.sql:/docker-entrypoint-initdb.d/fresh.sql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  wordpress:
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '8080:80'
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_PASSWORD

  nginx:
    restart: always
    links:
      - reactapp
      - wordpress
    ports:
      - '${NGINX_PORT}:80'

  reactapp:
    environment:
      - API_HOST
      - DEFAULT_PORT
