version: '2'
services:
  wordpress:
    image: larsson719/fabioschicken:wp-theme

  nginx:
    image: larsson719/fabioschicken:nginx

  reactapp:
    image: larsson719/fabioschicken:reactapp
    environment:
      - PRODUCTION=true
