version: '2'
services:
  db:
    restart: always
    image: mysql:5.7
    volumes:
      - "./mysqldata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    restart: always
    depends_on:
      - db
    links:
      - db
    image: wordpress:latest
    volumes:
      - "./wordpress:/var/www/html"
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress