// flow-typed signature: 6f98ec1840ee5dc3dd66a133c9bd256c
// flow-typed version: <<STUB>>/naught_v1.6.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'naught'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'naught' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'naught/lib/daemon' {
  declare module.exports: any;
}

declare module 'naught/lib/json_socket' {
  declare module.exports: any;
}

declare module 'naught/lib/log' {
  declare module.exports: any;
}

declare module 'naught/lib/main' {
  declare module.exports: any;
}

declare module 'naught/lib/master' {
  declare module.exports: any;
}

declare module 'naught/lib/start_daemon' {
  declare module.exports: any;
}

declare module 'naught/test/server1' {
  declare module.exports: any;
}

declare module 'naught/test/server10' {
  declare module.exports: any;
}

declare module 'naught/test/server2' {
  declare module.exports: any;
}

declare module 'naught/test/server3' {
  declare module.exports: any;
}

declare module 'naught/test/server4' {
  declare module.exports: any;
}

declare module 'naught/test/server5' {
  declare module.exports: any;
}

declare module 'naught/test/server6' {
  declare module.exports: any;
}

declare module 'naught/test/server7' {
  declare module.exports: any;
}

declare module 'naught/test/server8' {
  declare module.exports: any;
}

declare module 'naught/test/server9' {
  declare module.exports: any;
}

declare module 'naught/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'naught/lib/daemon.js' {
  declare module.exports: $Exports<'naught/lib/daemon'>;
}
declare module 'naught/lib/json_socket.js' {
  declare module.exports: $Exports<'naught/lib/json_socket'>;
}
declare module 'naught/lib/log.js' {
  declare module.exports: $Exports<'naught/lib/log'>;
}
declare module 'naught/lib/main.js' {
  declare module.exports: $Exports<'naught/lib/main'>;
}
declare module 'naught/lib/master.js' {
  declare module.exports: $Exports<'naught/lib/master'>;
}
declare module 'naught/lib/start_daemon.js' {
  declare module.exports: $Exports<'naught/lib/start_daemon'>;
}
declare module 'naught/test/server1.js' {
  declare module.exports: $Exports<'naught/test/server1'>;
}
declare module 'naught/test/server10.js' {
  declare module.exports: $Exports<'naught/test/server10'>;
}
declare module 'naught/test/server2.js' {
  declare module.exports: $Exports<'naught/test/server2'>;
}
declare module 'naught/test/server3.js' {
  declare module.exports: $Exports<'naught/test/server3'>;
}
declare module 'naught/test/server4.js' {
  declare module.exports: $Exports<'naught/test/server4'>;
}
declare module 'naught/test/server5.js' {
  declare module.exports: $Exports<'naught/test/server5'>;
}
declare module 'naught/test/server6.js' {
  declare module.exports: $Exports<'naught/test/server6'>;
}
declare module 'naught/test/server7.js' {
  declare module.exports: $Exports<'naught/test/server7'>;
}
declare module 'naught/test/server8.js' {
  declare module.exports: $Exports<'naught/test/server8'>;
}
declare module 'naught/test/server9.js' {
  declare module.exports: $Exports<'naught/test/server9'>;
}
declare module 'naught/test/test.js' {
  declare module.exports: $Exports<'naught/test/test'>;
}
