// flow-typed signature: cbc76c495c41fa1a84fed6241944c3ac
// flow-typed version: <<STUB>>/webpack-dev-middleware_v1.6.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/middleware'>;
}
